# Generated by Django 5.1.2 on 2024-10-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentlisting',
            old_name='item_type',
            new_name='contact_info',
        ),
        migrations.RenameField(
            model_name='equipmentlisting',
            old_name='location',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='equipmentlisting',
            name='condition',
        ),
        migrations.AddField(
            model_name='equipmentlisting',
            name='seller',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentlisting',
            name='site',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
