# Generated by Django 5.1.2 on 2024-10-29 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_rename_date_event_event_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentlisting',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='equipmentlisting',
            name='site',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='participants',
        ),
        migrations.AddField(
            model_name='meetup',
            name='title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentlisting',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='equipmentlisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
