# Generated by Django 5.1.2 on 2024-10-30 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_remove_equipmentlisting_contact_info_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meetup',
            new_name='Event',
        ),
    ]
