# Generated by Django 5.1.2 on 2024-10-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_rename_meetup_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentlisting',
            old_name='seller',
            new_name='seller',
        ),
    ]
