# Generated by Django 5.1.2 on 2024-10-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('preferences', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weather_conditions', models.TextField()),
                ('best_flying_times', models.TextField()),
                ('regulations', models.TextField()),
                ('safety_tips', models.TextField()),
            ],
        ),
    ]
