# Generated by Django 5.1.2 on 2024-10-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragliding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('weather', models.CharField(max_length=50)),
                ('best_flying_times', models.CharField(max_length=100)),
                ('local_regulations', models.TextField()),
                ('safety_tips', models.TextField()),
            ],
        ),
    ]
