# Generated by Django 5.1.2 on 2024-10-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragliding', '0002_siteinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='capacity',
            new_name='available_seats',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='time',
            new_name='departure_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='pickup_location',
            new_name='origin',
        ),
        migrations.AddField(
            model_name='ride',
            name='flight_plan',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='pilot_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
