# Generated by Django 5.1.2 on 2024-10-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragliding', '0003_rename_capacity_ride_available_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
