# Generated by Django 5.1.2 on 2024-10-29 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragliding', '0004_ride_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteInfo',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='best_flying_times',
            new_name='local_regulations',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='flight_plan',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pilot_name',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='site',
            name='regulations',
        ),
        migrations.RemoveField(
            model_name='site',
            name='safety_tips',
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='best_time',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
