# Generated by Django 5.1.2 on 2024-10-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragliding', '0005_delete_siteinfo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='SiteInfo',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='available_seats',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='driver',
        ),
        migrations.AddField(
            model_name='ride',
            name='date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='preferences',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='time',
            field=models.TimeField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ride',
            name='origin',
            field=models.CharField(max_length=255),
        ),
    ]
