# Generated by Django 5.1.2 on 2024-10-29 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0002_sustainabilitypractice_delete_sustainablepractice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incentive',
            old_name='reward_points',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='sustainabilitypractice',
            old_name='benefits',
            new_name='success_story',
        ),
        migrations.RemoveField(
            model_name='incentive',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='incentive',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sustainabilitypractice',
            name='implementation_steps',
        ),
        migrations.RemoveField(
            model_name='sustainabilitypractice',
            name='title',
        ),
        migrations.AddField(
            model_name='incentive',
            name='practice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sustainability.sustainabilitypractice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incentive',
            name='reward',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
